# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- netlify.toml

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# Site settings
url: ''
baseurl: ''
title: 'UW Astronomy Gaia Data Sprint'
description: 'Welcome!'
permalink: pretty
logo: "https://dawgdaze.fyp.uw.edu/wp-content/uploads/2021/09/final_uw_astro_sticker-300x300.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: Data Resources
  url: /about/
- title: Organizing Members
  url: /soc/
- title: 
  url: /tips/
- title: Sponsors
  url: /sponsors/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://cdn.mos.cms.futurecdn.net/F9A5R54nwwkTHFByZNrsvk.gif"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
